name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: environment
    attribute:
      label: Environmental info
      description: Add any info about the environment: Browser, Device, OS etc.
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, logs etc.
